<?php header('content-type: application/json') ?>
{
    "CityId": 218,
    "ExcludeIds": null,
    "Query": null,
    "Items": [{
        "Id": 216959,
        "Name": "Let\u0027s Sushi",
        "Address": "13B Quốc Tử Giám, Quận Đống Đa, Hà Nội",
        "AvgRating": 7.368000,
        "AvgRatingText": "7.4",
        "RestaurantStatus": 2,
        "Phone": "0963 682 404",
        "PhotoUrl": "https://media.foody.vn/res/g22/216959/prof/s640x400/foody-mobile-sushi-jpg-822-636162882555040762.jpg",
        "TotalReviews": 30,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 248,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/let-s-sushi",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0262290000000,
        "Longitude": 105.8375620000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/vnsama",
            "reviewUserDisplayName": "Vnsama",
            "reviewUserAvatar": "https://media.foody.vn/usr/g937/9362297/avt/c100x100/foody-avatar-506-636415342116963333.jpg",
            "reviewUrl": "/ha-noi/let-s-sushi/binh-luan-1729681",
            "AvgRatingText": "6.8",
            "ShortReview": false,
            "ReviewId": 1729681,
            "Comment": "Mình order 1 suất gồm nigiri lươn, nigiri cá trích, gunkan trứng chuồn, gunkan trứng cua vs 1 bánh xèo. \nNigiri vs gunkan thì ăn cũng ngon, chỉ là ship cho mình gunkan 3 chuồn 1 cua thay vì 2 chuồn 2 ...",
            "UserId": 9362297,
            "Username": "",
            "UserAvatar": "foody-avatar-506-636415342116963333.jpg",
            "UserGender": "",
            "UserFirstName": "Vnsama",
            "UserLastName": "",
            "AvgRating": 6.800000
        }, {
            "reviewProfileUrl": "/thanh-vien/likho",
            "reviewUserDisplayName": "likho",
            "reviewUserAvatar": "https://media.foody.vn/usr/g93/929962/avt/c100x100/foody-avatar-351-636387589584901247.jpg",
            "reviewUrl": "/ha-noi/let-s-sushi/binh-luan-1724531",
            "AvgRatingText": "3.0",
            "ShortReview": false,
            "ReviewId": 1724531,
            "Comment": "Mình đặt trên delivery now , đợi hơn 50p mà lại nhận đc một cái bánh cháy và tất nhiên là đắng . Tại sao bạn bếp không nghĩ đến cảm nhận của khách khi đợi quá lâu va nhận đc 1 cái bánh cháy . Sushi bình ...",
            "UserId": 929962,
            "Username": "",
            "UserAvatar": "foody-avatar-351-636387589584901247.jpg",
            "UserGender": "F",
            "UserFirstName": "likho",
            "UserLastName": "",
            "AvgRating": 3.000000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/let-s-sushi/album-anh",
        "ResUrlReviews": "/ha-noi/let-s-sushi/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/let-s-sushi",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 216959,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "let-s-sushi",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 216959,
        "MainCategoryId": 0,
        "TotalSaves": 506,
        "Status": 0,
        "TotalSavesFormat": "506",
        "TotalReviewsFormat": "30",
        "TotalPicturesFormat": "248",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/let-s-sushi/goi-mon",
        "HasVideo": true,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 70304,
        "Name": "Cháo Sườn Huyền Anh - Đồng Xuân",
        "Address": "14 Đồng Xuân, Quận Hoàn Kiếm, Hà Nội",
        "AvgRating": 7.204000,
        "AvgRatingText": "7.2",
        "RestaurantStatus": 2,
        "Phone": "1900 2042 - 0915 550 646 - 0981 568 168",
        "PhotoUrl": "https://media.foody.vn/res/g8/70304/prof/s640x400/foody-mobile-chao-suon-dong-xuan--865-635851239130539281.jpg",
        "TotalReviews": 150,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 423,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/chao-suon-dong-xuan",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0380863000000,
        "Longitude": 105.8488199000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/coniubome",
            "reviewUserDisplayName": "Loan Thanh nguyen",
            "reviewUserAvatar": "https://media.foody.vn/usr/g92/919903/avt/c100x100/foody-avatar-791-636437450773477280.jpg",
            "reviewUrl": "/ha-noi/chao-suon-dong-xuan/binh-luan-1731240",
            "AvgRatingText": "7.6",
            "ShortReview": false,
            "ReviewId": 1731240,
            "Comment": "Mình thích ăn cháo nên phải ra đây ngay thử ăn quán nổi tiếng này.\nCũng là kiểu cháo bột mình không thích lắm.\nBát khá to và đầy đủ, ăn được. Chứ nói về vị mình không biết đánh giá thêz nào là ngon vì ...",
            "UserId": 919903,
            "Username": "nguyen",
            "UserAvatar": "foody-avatar-791-636437450773477280.jpg",
            "UserGender": "F",
            "UserFirstName": "Loan Thanh",
            "UserLastName": "nguyen",
            "AvgRating": 7.600000
        }, {
            "reviewProfileUrl": "/thanh-vien/xiuying135",
            "reviewUserDisplayName": "xiuying135",
            "reviewUserAvatar": "https://media.foody.vn/usr/g954/9537337/avt/c100x100/xiuying135-avatar-426-636437031765101733.jpg",
            "reviewUrl": "/ha-noi/chao-suon-dong-xuan/binh-luan-1726821",
            "AvgRatingText": "7.6",
            "ShortReview": false,
            "ReviewId": 1726821,
            "Comment": "Mình mua suất không quẩy là 30k. Cháo ăn rất ngon, sườn mềm mà nhiều thịt nữa chứ. 1 hộp cháo đầy ăn no căng bụng. Cháo này trời lạnh lạnh mà ăn là cực hợp luôn cả có thêm 2 gói ớt bột và tiêu thêm ít ...",
            "UserId": 9537337,
            "Username": "",
            "UserAvatar": "xiuying135-avatar-426-636437031765101733.jpg",
            "UserGender": "",
            "UserFirstName": "xiuying135",
            "UserLastName": "",
            "AvgRating": 7.600000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/chao-suon-dong-xuan/album-anh",
        "ResUrlReviews": "/ha-noi/chao-suon-dong-xuan/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/chao-suon-dong-xuan",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 70304,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "chao-suon-dong-xuan",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 70304,
        "MainCategoryId": 0,
        "TotalSaves": 842,
        "Status": 0,
        "TotalSavesFormat": "842",
        "TotalReviewsFormat": "150",
        "TotalPicturesFormat": "423",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/chao-suon-dong-xuan/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 655611,
        "Name": "HealthWich Vietnam - Lương Ngọc Quyến",
        "Address": "46 Lương Ngọc Quyến, Quận Hoàn Kiếm, Hà Nội",
        "AvgRating": 8.656000,
        "AvgRatingText": "8.7",
        "RestaurantStatus": 2,
        "Phone": "(024) 22 101 313",
        "PhotoUrl": "https://media.foody.vn/res/g66/655611/prof/s640x400/foody-mobile-hep-jpg-601-636421048905011774.jpg",
        "TotalReviews": 25,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 73,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/healthwich-vietnam-luong-ngoc-quyen",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0347280000000,
        "Longitude": 105.8515390000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/gaulun1441999",
            "reviewUserDisplayName": "Hanh Nguyen",
            "reviewUserAvatar": "https://media.foody.vn/usr/g52/512429/avt/c100x100/foody-avatar-397-635930514575500147.jpg",
            "reviewUrl": "/ha-noi/healthwich-vietnam-luong-ngoc-quyen/binh-luan-1690321",
            "AvgRatingText": "8.8",
            "ShortReview": false,
            "ReviewId": 1690321,
            "Comment": "BONJOUR, Y\u0027ALL🌈🌈🌈🌈\nLại là pé Hạnh nạ🍑🍑🍑🍑🍑🍑🍑🍑\nNgay giây phút này mưa đang vl các ae ạ🌧🌧🌧 thích vl hề hề🌚🌝 ấy thế mà bụng lại đói nên là lại Healthwich thôiiii💥💥 💥\n\nChắc chắn phải order ...",
            "UserId": 512429,
            "Username": "Nguyen",
            "UserAvatar": "foody-avatar-397-635930514575500147.jpg",
            "UserGender": "F",
            "UserFirstName": "Hanh",
            "UserLastName": "Nguyen",
            "AvgRating": 8.800000
        }, {
            "reviewProfileUrl": "/thanh-vien/gaulun1441999",
            "reviewUserDisplayName": "Hanh Nguyen",
            "reviewUserAvatar": "https://media.foody.vn/usr/g52/512429/avt/c100x100/foody-avatar-397-635930514575500147.jpg",
            "reviewUrl": "/ha-noi/healthwich-vietnam-luong-ngoc-quyen/binh-luan-1682087",
            "AvgRatingText": "7.0",
            "ShortReview": false,
            "ReviewId": 1682087,
            "Comment": "Bánh mì đặc biệt lúc ship ghi là Luxury làm t nhìn chưa gì đã có thiện cảm✨✨✨ bánh Gà nướng🍗🍗 nữa t đều chọn đổi sang bánh mì ngũ cốc 16cm🌾🌾🌾🌾\n\nCả 2 t đều order sốt Bbq nhưng t k hề nếm đc vị sốt🤷🏼‍♀️🤷🏼‍♀️🤷🏼‍♀️ ...",
            "UserId": 512429,
            "Username": "Nguyen",
            "UserAvatar": "foody-avatar-397-635930514575500147.jpg",
            "UserGender": "F",
            "UserFirstName": "Hanh",
            "UserLastName": "Nguyen",
            "AvgRating": 7.000000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/healthwich-vietnam-luong-ngoc-quyen/album-anh",
        "ResUrlReviews": "/ha-noi/healthwich-vietnam-luong-ngoc-quyen/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/healthwich-vietnam-luong-ngoc-quyen",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 655611,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "healthwich-vietnam-luong-ngoc-quyen",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 655611,
        "MainCategoryId": 0,
        "TotalSaves": 205,
        "Status": 0,
        "TotalSavesFormat": "205",
        "TotalReviewsFormat": "25",
        "TotalPicturesFormat": "73",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/healthwich-vietnam-luong-ngoc-quyen/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 673171,
        "Name": "Royaltea - Trà Sữa Hồng Kông - Hồ Tùng Mậu",
        "Address": "62 Hồ Tùng Mậu, Quận Cầu Giấy, Hà Nội",
        "AvgRating": 6.576000,
        "AvgRatingText": "6.6",
        "RestaurantStatus": 2,
        "Phone": "0912 640 079 - 0988 181 512 - 0915 548 787",
        "PhotoUrl": "https://media.foody.vn/res/g68/673171/prof/s640x400/foody-mobile-459-jpg-753-636352832676344576.jpg",
        "TotalReviews": 16,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 32,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0382470000000,
        "Longitude": 105.7733480000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/ohmygod2299",
            "reviewUserDisplayName": "Huyền Lee",
            "reviewUserAvatar": "https://media.foody.vn/usr/g958/9577171/avt/c100x100/foody-avatar-950-636400630798783795.jpg",
            "reviewUrl": "/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau/binh-luan-1726222",
            "AvgRatingText": "4.8",
            "ShortReview": false,
            "ReviewId": 1726222,
            "Comment": "Hôm qua mình or 1 trà olong sakura kem cheese trên deli. Xác nhận đơn và giao hàng khá nhanh. Trà thanh và kem cheese đậm vị. Nói chung chất lượng oke\nMong quán có thêm mã giảm tổng bill nhiều hơn ^^",
            "UserId": 9577171,
            "Username": "Lee",
            "UserAvatar": "foody-avatar-950-636400630798783795.jpg",
            "UserGender": "F",
            "UserFirstName": "Huyền",
            "UserLastName": "Lee",
            "AvgRating": 4.800000
        }, {
            "reviewProfileUrl": "/thanh-vien/hue.dang",
            "reviewUserDisplayName": "minhhue  dang",
            "reviewUserAvatar": "https://media.foody.vn/usr/g57/564792/avt/c100x100/foody-avatar-403-635611457113052532.jpg",
            "reviewUrl": "/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau/binh-luan-1720406",
            "AvgRatingText": "7.2",
            "ShortReview": false,
            "ReviewId": 1720406,
            "Comment": "Vốn mình không phải tín đồ trà sữa vì cũng không phải trẻ trung gì, từ đầu năm tới giờ uống trên đầu ngón tay và cũng chưa uống ở Royal bao giờ. Hôm qua được mời nên ghé vào đây vì gần nhà và cũng vì ...",
            "UserId": 564792,
            "Username": "dang",
            "UserAvatar": "foody-avatar-403-635611457113052532.jpg",
            "UserGender": null,
            "UserFirstName": "minhhue ",
            "UserLastName": "dang",
            "AvgRating": 7.200000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau/album-anh",
        "ResUrlReviews": "/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 673171,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "royaltea-tra-sua-hong-kong-ho-tung-mau",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 673171,
        "MainCategoryId": 0,
        "TotalSaves": 26,
        "Status": 0,
        "TotalSavesFormat": "26",
        "TotalReviewsFormat": "16",
        "TotalPicturesFormat": "32",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/royaltea-tra-sua-hong-kong-ho-tung-mau/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 85327,
        "Name": "Highlands Coffee - Hoàng Đạo Thúy",
        "Address": "17T1 Hoàng Đạo Thúy, Quận Cầu Giấy, Hà Nội",
        "AvgRating": 6.382000,
        "AvgRatingText": "6.4",
        "RestaurantStatus": 2,
        "Phone": "(024) 62 812 932",
        "PhotoUrl": "https://media.foody.vn/res/g9/85327/prof/s640x400/foody-mobile-hmb-h-jpg-132-635785351038809223.jpg",
        "TotalReviews": 48,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 179,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/highlands-coffee-hoang-dao-thuy",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0084204786725,
        "Longitude": 105.8019044995307,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/honganh8300",
            "reviewUserDisplayName": "Đặng Hồng Anh",
            "reviewUserAvatar": "https://media.foody.vn/usr/g952/9518309/avt/c100x100/foody-avatar-365-636393528912012270.jpg",
            "reviewUrl": "/ha-noi/highlands-coffee-hoang-dao-thuy/binh-luan-1701212",
            "AvgRatingText": "3.6",
            "ShortReview": false,
            "ReviewId": 1701212,
            "Comment": "Highlands coffee nhìn chung thì cũng thuộc loại sang chảnh các thứ rồi. Không gian ở đây tương đối là rộng rãi thoải maia. Tuy nhiên lại hơi nóng ( dù có chạy điều hòa). Hơi ít bàn nữa ạ, mình đi tầm ...",
            "UserId": 9518309,
            "Username": "",
            "UserAvatar": "foody-avatar-365-636393528912012270.jpg",
            "UserGender": "F",
            "UserFirstName": "Đặng Hồng Anh",
            "UserLastName": "",
            "AvgRating": 3.600000
        }, {
            "reviewProfileUrl": "/thanh-vien/0967985888",
            "reviewUserDisplayName": "tulii97",
            "reviewUserAvatar": "https://media.foody.vn/usr/g929/9286820/avt/c100x100/0967985888-avatar-559-636383393707785813.jpg",
            "reviewUrl": "/ha-noi/highlands-coffee-hoang-dao-thuy/binh-luan-1694170",
            "AvgRatingText": "8.0",
            "ShortReview": false,
            "ReviewId": 1694170,
            "Comment": "🍂Không gian khá rộng rãi , nvien thái độ bthg , k đc nhiệt tình lắm , bọn mình order 2 cốc nc và 1 tira , 1 cheesecake chanh leo , nhanh dã man luôn chưa đầy 10\u0027 đã có đồ rồi mặc dù hôm đấy rõ là đôngggg ...",
            "UserId": 9286820,
            "Username": "",
            "UserAvatar": "0967985888-avatar-559-636383393707785813.jpg",
            "UserGender": "F",
            "UserFirstName": "tulii97",
            "UserLastName": "",
            "AvgRating": 8.000000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/highlands-coffee-hoang-dao-thuy/album-anh",
        "ResUrlReviews": "/ha-noi/highlands-coffee-hoang-dao-thuy/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/highlands-coffee-hoang-dao-thuy",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 85327,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "highlands-coffee-hoang-dao-thuy",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 85327,
        "MainCategoryId": 0,
        "TotalSaves": 49,
        "Status": 0,
        "TotalSavesFormat": "49",
        "TotalReviewsFormat": "48",
        "TotalPicturesFormat": "179",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/highlands-coffee-hoang-dao-thuy/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 262461,
        "Name": "Thiên Di Quán - Ẩm Thực Hong Kong - Lý Thường Kiệt",
        "Address": "26 Lý Thường Kiệt, Quận Hoàn Kiếm, Hà Nội",
        "AvgRating": 6.720000,
        "AvgRatingText": "6.7",
        "RestaurantStatus": 2,
        "Phone": "0902 552 358",
        "PhotoUrl": "https://media.foody.vn/res/g27/262461/prof/s640x400/foody-mobile-foody-mobile-1-jpg-6-275-636380417881998445.jpg",
        "TotalReviews": 10,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 91,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/thien-di-quan-am-thuc-hong-kong",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0225950000000,
        "Longitude": 105.8532199000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/jul.liy",
            "reviewUserDisplayName": "Cao Trang",
            "reviewUserAvatar": "https://media.foody.vn/usr/g879/8783985/avt/c100x100/jul-liy-avatar-178-636421846255482585.jpg",
            "reviewUrl": "/ha-noi/thien-di-quan-am-thuc-hong-kong/binh-luan-1694424",
            "AvgRatingText": "7.8",
            "ShortReview": false,
            "ReviewId": 1694424,
            "Comment": "Những món mình thấy ngon nè: bánh bao kim sa, cháo trứng bác thảo, vịt nướng có nước chấm ngọt ngọt hay phết, bánh cuốn cũng ok\nDimsum cảm giác nhân hơi bứ, chưa được kiểu mềm mướt cho lắm. \n7.5/10",
            "UserId": 8783985,
            "Username": "Trang",
            "UserAvatar": "jul-liy-avatar-178-636421846255482585.jpg",
            "UserGender": "F",
            "UserFirstName": "Cao",
            "UserLastName": "Trang",
            "AvgRating": 7.800000
        }, {
            "reviewProfileUrl": "/thanh-vien/quynhanhbui.92",
            "reviewUserDisplayName": "Anh Quỳnh",
            "reviewUserAvatar": "https://media.foody.vn/usr/g38/374385/avt/c100x100/foody-avatar-839-636321527465221983.jpg",
            "reviewUrl": "/ha-noi/thien-di-quan-am-thuc-hong-kong/binh-luan-1670969",
            "AvgRatingText": "1.0",
            "ShortReview": false,
            "ReviewId": 1670969,
            "Comment": "Mình rất rất thích dimsum và thường ăn ở Dimsum Corner. Nay cũng lên cơn vật dimsum mà ăn mãi ở DC rồi nên muốn đổi gió. Tìm được quán này qua Foody vậy là đến ăn thử coi. Tóm váy lại một câu là quá THẤT ...",
            "UserId": 374385,
            "Username": "",
            "UserAvatar": "foody-avatar-839-636321527465221983.jpg",
            "UserGender": "",
            "UserFirstName": "Anh Quỳnh",
            "UserLastName": "",
            "AvgRating": 1.000000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/thien-di-quan-am-thuc-hong-kong/album-anh",
        "ResUrlReviews": "/ha-noi/thien-di-quan-am-thuc-hong-kong/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.tablenow.vn/ha-noi/thien-di-quan-am-thuc-hong-kong",
            "Title": "tablenow.vn",
            "Text": "Đặt bàn ",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-tablenow.png",
            "BackgroundColor": "#E87C3A",
            "RestaurantId": 262461,
            "Description": null
        }, {
            "Id": 2,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/thien-di-quan-am-thuc-hong-kong",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 262461,
            "Description": null
        }],
        "TotalService": 2,
        "UrlRewriteName": "thien-di-quan-am-thuc-hong-kong",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 262461,
        "MainCategoryId": 0,
        "TotalSaves": 101,
        "Status": 0,
        "TotalSavesFormat": "101",
        "TotalReviewsFormat": "10",
        "TotalPicturesFormat": "91",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": true,
        "IsDelivery": true,
        "BookingUrl": "/ha-noi/thien-di-quan-am-thuc-hong-kong",
        "DeliveryUrl": "/ha-noi/thien-di-quan-am-thuc-hong-kong/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 252881,
        "Name": "Trà Sữa Gong Cha - 貢茶 - Lý Thường Kiệt",
        "Address": "56 Lý Thường Kiệt, Quận Hoàn Kiếm, Hà Nội",
        "AvgRating": 7.068000,
        "AvgRatingText": "7.1",
        "RestaurantStatus": 2,
        "Phone": "1900 2042 - (024) 37 568 989",
        "PhotoUrl": "https://media.foody.vn/res/g26/252881/prof/s640x400/foody-mobile-gongcha-jpg-805-636162011618326369.jpg",
        "TotalReviews": 298,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 1350,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/tra-sua-gong-cha",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0248670000000,
        "Longitude": 105.8454669000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/vipmoc9x",
            "reviewUserDisplayName": "Quyên Bò",
            "reviewUserAvatar": "https://media.foody.vn/usr/g89/886224/avt/c100x100/foody-avatar-721-636140320717789381.jpg",
            "reviewUrl": "/ha-noi/tra-sua-gong-cha/binh-luan-1727196",
            "AvgRatingText": "6.0",
            "ShortReview": false,
            "ReviewId": 1727196,
            "Comment": "Hôm nay m và bạn có gọi 4 cốc trà + trà sữa về uống. Lúc đặt xong nhập mã khuyến mãi mà không sử dụng đc, thế là toi luôn 30% hiuhiu, được cái freeship. Quán nên xem lại hệ thống, nếu k còn khuyến mãi ...",
            "UserId": 886224,
            "Username": "",
            "UserAvatar": "foody-avatar-721-636140320717789381.jpg",
            "UserGender": "F",
            "UserFirstName": "Quyên Bò",
            "UserLastName": "",
            "AvgRating": 6.000000
        }, {
            "reviewProfileUrl": "/thanh-vien/phamthanh104",
            "reviewUserDisplayName": "phamthanh104",
            "reviewUserAvatar": "https://media.foody.vn/default/s100/user-default-female.png",
            "reviewUrl": "/ha-noi/tra-sua-gong-cha/binh-luan-1719011",
            "AvgRatingText": "8.8",
            "ShortReview": false,
            "ReviewId": 1719011,
            "Comment": "Mình k mặn mà lắm cái vị matcha thế mà thấy uống matcha ở Gongcha pha vừa mà thơm nữa. Thật sự rất ưng cái bụng. Đợt biết đông mà vẫn cố gắng đợi luôn. Bh có cái dv Deli này cx tiện nữa ngồi nhà od vs ...",
            "UserId": 9836215,
            "Username": "",
            "UserAvatar": null,
            "UserGender": "",
            "UserFirstName": "phamthanh104",
            "UserLastName": "",
            "AvgRating": 8.800000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/tra-sua-gong-cha/album-anh",
        "ResUrlReviews": "/ha-noi/tra-sua-gong-cha/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/tra-sua-gong-cha",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 252881,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "tra-sua-gong-cha",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 252881,
        "MainCategoryId": 0,
        "TotalSaves": 782,
        "Status": 0,
        "TotalSavesFormat": "782",
        "TotalReviewsFormat": "298",
        "TotalPicturesFormat": "1.4K",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/tra-sua-gong-cha/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 696762,
        "Name": "Vua Gà Mạnh Hoạch - Giang Văn Minh",
        "Address": "32 Giang Văn Minh, Quận Ba Đình, Hà Nội",
        "AvgRating": 8.000000,
        "AvgRatingText": "8.0",
        "RestaurantStatus": 2,
        "Phone": "0919 778 842",
        "PhotoUrl": "https://media.foody.vn/res/g70/696762/prof/s640x400/foody-mobile-ga-met-jpg.jpg",
        "TotalReviews": 1,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 15,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/vua-ga-manh-hoach-giang-van-minh",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0332540000000,
        "Longitude": 105.8271020000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/thao.hua-thi-phuong",
            "reviewUserDisplayName": "Thaohua",
            "reviewUserAvatar": "https://media.foody.vn/usr/g880/8793951/avt/c100x100/thao-hua-thi-phuong-avatar-880-636295803301775947.jpg",
            "reviewUrl": "/ha-noi/vua-ga-manh-hoach-giang-van-minh/binh-luan-1738035",
            "AvgRatingText": "8.0",
            "ShortReview": false,
            "ReviewId": 1738035,
            "Comment": "Mình cực thích ăn các món từ gà nên lùng ra được quán này ưng lắm lắm!\nChân gà rang muối đậm đà, chân gà khá to, bên ngoài giòn giòn thơm nức mũi, chấm thêm sốt ớt cay ngọt hoặc muối chanh ăn hay hay ...",
            "UserId": 8793951,
            "Username": "",
            "UserAvatar": "thao-hua-thi-phuong-avatar-880-636295803301775947.jpg",
            "UserGender": "F",
            "UserFirstName": "Thaohua",
            "UserLastName": "",
            "AvgRating": 8.000000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/vua-ga-manh-hoach-giang-van-minh/album-anh",
        "ResUrlReviews": "/ha-noi/vua-ga-manh-hoach-giang-van-minh/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [],
        "TotalService": 0,
        "UrlRewriteName": "vua-ga-manh-hoach-giang-van-minh",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 696762,
        "MainCategoryId": 0,
        "TotalSaves": 0,
        "Status": 0,
        "TotalSavesFormat": "0",
        "TotalReviewsFormat": "1",
        "TotalPicturesFormat": "15",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": false,
        "BookingUrl": "",
        "DeliveryUrl": "",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 694495,
        "Name": "Food House - Hồ Đắc Di",
        "Address": "157 Hồ Đắc Di, Quận Đống Đa, Hà Nội",
        "AvgRating": 8.150000,
        "AvgRatingText": "8.2",
        "RestaurantStatus": 2,
        "Phone": "0981 626 157",
        "PhotoUrl": "https://media.foody.vn/res/g70/694495/prof/s640x400/foody-mobile-hlk-jpg.jpg",
        "TotalReviews": 4,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 15,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/food-house-ho-dac-di",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0133460000000,
        "Longitude": 105.8269820000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/k.tung2410",
            "reviewUserDisplayName": "Tùng Kiều",
            "reviewUserAvatar": "https://media.foody.vn/usr/g12/110106/avt/c100x100/foody-avatar-233-636442065292794582.jpg",
            "reviewUrl": "/ha-noi/food-house-ho-dac-di/binh-luan-1737890",
            "AvgRatingText": "7.4",
            "ShortReview": false,
            "ReviewId": 1737890,
            "Comment": "Hqua 2 vk ck mình ghé quán lần đầu. Lần trc ăn hụt vì đi cuối tuần hết chỗ.\nQuán k quá rộng nhưng gọn gàng. Nhân viên nhiệt tình. Có điều hơi chậm. Mình phải chờ 30p mới có lẩu trong khi quán k đông.\nNước ...",
            "UserId": 110106,
            "Username": "Kiều",
            "UserAvatar": "foody-avatar-233-636442065292794582.jpg",
            "UserGender": "M",
            "UserFirstName": "Tùng",
            "UserLastName": "Kiều",
            "AvgRating": 7.400000
        }, {
            "reviewProfileUrl": "/thanh-vien/chuyenmklc",
            "reviewUserDisplayName": "Chuyn",
            "reviewUserAvatar": "https://media.foody.vn/usr/g825/8249148/avt/c100x100/foody-avatar-448-636427061470964309.jpg",
            "reviewUrl": "/ha-noi/food-house-ho-dac-di/binh-luan-1732926",
            "AvgRatingText": "9.2",
            "ShortReview": false,
            "ReviewId": 1732926,
            "Comment": "Hôm khai trương quán khuyến mại 199k 1 nồi lẩu 9 tầng mây. Rủ 2 chị e nữa đi ăn, đều là tín đồ của thịt và nhịn đói lâu ngày.\nĐến thấy không gian quán nhỏ nhưng được cái thoáng, có 3 tầng, khá nhiều bàn ...",
            "UserId": 8249148,
            "Username": "",
            "UserAvatar": "foody-avatar-448-636427061470964309.jpg",
            "UserGender": "F",
            "UserFirstName": "Chuyn",
            "UserLastName": "",
            "AvgRating": 9.200000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/food-house-ho-dac-di/album-anh",
        "ResUrlReviews": "/ha-noi/food-house-ho-dac-di/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.tablenow.vn/ha-noi/food-house-ho-dac-di",
            "Title": "tablenow.vn",
            "Text": "Đặt bàn ",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-tablenow.png",
            "BackgroundColor": "#E87C3A",
            "RestaurantId": 694495,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "food-house-ho-dac-di",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 694495,
        "MainCategoryId": 0,
        "TotalSaves": 45,
        "Status": 0,
        "TotalSavesFormat": "45",
        "TotalReviewsFormat": "4",
        "TotalPicturesFormat": "15",
        "IsAds": true,
        "MobileBgColor": "#000000",
        "IsBooking": true,
        "IsDelivery": false,
        "BookingUrl": "/ha-noi/food-house-ho-dac-di",
        "DeliveryUrl": "",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 672122,
        "Name": "Trà Sữa Bobapop - Quán Thánh",
        "Address": "114 Quán Thánh, Quận Ba Đình, Hà Nội",
        "AvgRating": 6.988000,
        "AvgRatingText": "7.0",
        "RestaurantStatus": 2,
        "Phone": "(024) 66 879 197",
        "PhotoUrl": "https://media.foody.vn/res/g68/672122/prof/s640x400/foody-mobile-416-jpg-630-636349468607155362.jpg",
        "TotalReviews": 16,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 90,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/tra-sua-bobapop-quan-thanh",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0422450000000,
        "Longitude": 105.8432080000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/tranghoang9357",
            "reviewUserDisplayName": "Trangg Linh",
            "reviewUserAvatar": "https://media.foody.vn/usr/g203/2029705/avt/c100x100/tranghoang9357-avatar-527-636319194201006647.jpg",
            "reviewUrl": "/ha-noi/tra-sua-bobapop-quan-thanh/binh-luan-1685841",
            "AvgRatingText": "5.8",
            "ShortReview": false,
            "ReviewId": 1685841,
            "Comment": "Hôm mình đi là vào ngày chủ nhật cùng vs 3 người khác. 1 bạn gọi trà xanh matcha nhật bản, 2 ng gọi trà gạo nâu, mình gọi trà xanh kiwi. Về trà xanh kiwi khá ổn nhưng trà xanh matcha thì đắng hơn thuốc ...",
            "UserId": 2029705,
            "Username": "Linh",
            "UserAvatar": "tranghoang9357-avatar-527-636319194201006647.jpg",
            "UserGender": "F",
            "UserFirstName": "Trangg",
            "UserLastName": "Linh",
            "AvgRating": 5.800000
        }, {
            "reviewProfileUrl": "/thanh-vien/petal_l0v3_chul",
            "reviewUserDisplayName": "Bui Nhat Quyen",
            "reviewUserAvatar": "https://media.foody.vn/usr/g172/1719698/avt/c100x100/petal_l0v3_chul-avatar-718-636044584767715613.jpg",
            "reviewUrl": "/ha-noi/tra-sua-bobapop-quan-thanh/binh-luan-1667146",
            "AvgRatingText": "7.4",
            "ShortReview": false,
            "ReviewId": 1667146,
            "Comment": "Vừa ngồi Bobapop Quán Thánh chiều nay nên review luôn cho nóng 😂\n\n- Vị trí: Lấy mốc cũng khá khó. Quán Thánh đường 1 chiều nên cứ đi chỗ Phan Đình Phùng rẽ ra Quán Thánh là đúng đường nhất, quán bên ...",
            "UserId": 1719698,
            "Username": "Nhat Quyen",
            "UserAvatar": "petal_l0v3_chul-avatar-718-636044584767715613.jpg",
            "UserGender": "F",
            "UserFirstName": "Bui",
            "UserLastName": "Nhat Quyen",
            "AvgRating": 7.400000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/tra-sua-bobapop-quan-thanh/album-anh",
        "ResUrlReviews": "/ha-noi/tra-sua-bobapop-quan-thanh/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/tra-sua-bobapop-quan-thanh",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 672122,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "tra-sua-bobapop-quan-thanh",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 672122,
        "MainCategoryId": 0,
        "TotalSaves": 8,
        "Status": 0,
        "TotalSavesFormat": "8",
        "TotalReviewsFormat": "16",
        "TotalPicturesFormat": "90",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/tra-sua-bobapop-quan-thanh/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 145394,
        "Name": "Cha Go Tea \u0026 Caf\u0027e - Hàng Buồm",
        "Address": "89 Hàng Buồm, Quận Hoàn Kiếm, Hà Nội",
        "AvgRating": 7.396000,
        "AvgRatingText": "7.4",
        "RestaurantStatus": 2,
        "Phone": "(024) 62 999 994",
        "PhotoUrl": "https://media.foody.vn/res/g15/145394/prof/s640x400/foody-mobile-chago-jpg-842-635761777666543784.jpg",
        "TotalReviews": 313,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 1176,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/chago-tea-caf-e-hang-buom",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0357920000000,
        "Longitude": 105.8511130000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/hthy3300",
            "reviewUserDisplayName": "Hà Thúy",
            "reviewUserAvatar": "https://media.foody.vn/usr/g994/9933990/avt/c100x100/foody-avatar-724-636444846001308622.jpg",
            "reviewUrl": "/ha-noi/chago-tea-caf-e-hang-buom/binh-luan-1737742",
            "AvgRatingText": "5.2",
            "ShortReview": false,
            "ReviewId": 1737742,
            "Comment": "Trà sữa vị trí dễ tìm và nhiều loại để lựa chọn, uống cũng khá ổn, nhưng vị thì mình không thích lắm, nếu được thì nên thêm nhiều sữa hơn vì trong trà sữa hơi nhiều nước hay sao ấy, sẽ quay lại vào vài ...",
            "UserId": 9933990,
            "Username": "Thúy",
            "UserAvatar": "foody-avatar-724-636444846001308622.jpg",
            "UserGender": "F",
            "UserFirstName": "Hà",
            "UserLastName": "Thúy",
            "AvgRating": 5.200000
        }, {
            "reviewProfileUrl": "/thanh-vien/chloepham2810",
            "reviewUserDisplayName": "Chloe Phạm",
            "reviewUserAvatar": "https://media.foody.vn/usr/g958/9572857/avt/c100x100/foody-avatar-329-636400361724284110.jpg",
            "reviewUrl": "/ha-noi/chago-tea-caf-e-hang-buom/binh-luan-1737730",
            "AvgRatingText": "7.6",
            "ShortReview": false,
            "ReviewId": 1737730,
            "Comment": "Đậm vị trà nhưng hơi bị ngọt dù mình đã giảm 30% 😢. Không gian hơi hẹp và tối nhưng đẹp, độc đáo.",
            "UserId": 9572857,
            "Username": "",
            "UserAvatar": "foody-avatar-329-636400361724284110.jpg",
            "UserGender": "F",
            "UserFirstName": "Chloe Phạm",
            "UserLastName": "",
            "AvgRating": 7.600000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/chago-tea-caf-e-hang-buom/album-anh",
        "ResUrlReviews": "/ha-noi/chago-tea-caf-e-hang-buom/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/chago-tea-caf-e-hang-buom",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 145394,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "chago-tea-caf-e-hang-buom",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 145394,
        "MainCategoryId": 0,
        "TotalSaves": 919,
        "Status": 0,
        "TotalSavesFormat": "919",
        "TotalReviewsFormat": "313",
        "TotalPicturesFormat": "1.2K",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/chago-tea-caf-e-hang-buom/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }, {
        "Id": 8920,
        "Name": "Nhà Hàng 123 - Kim Mã",
        "Address": "365 Kim Mã, Quận Ba Đình, Hà Nội",
        "AvgRating": 6.802000,
        "AvgRatingText": "6.8",
        "RestaurantStatus": 2,
        "Phone": "(024) 37 711 123 - (024) 37 711 333",
        "PhotoUrl": "https://media.foody.vn/res/g1/8920/prof/s640x400/foody-mobile-com123-jpg-857-636199007925224579.jpg",
        "TotalReviews": 87,
        "TotalFavourites": 0,
        "TotalViews": 0,
        "TotalPictures": 272,
        "TotalCheckIns": 0,
        "Url": "/ha-noi/nha-hang-com-123-kim-ma",
        "Tags": null,
        "Description": null,
        "Note": {
            "RestaurantId": 0,
            "UserId": 0,
            "ListId": null,
            "ListName": null,
            "CreatedOn": "\/Date(-62135596800000)\/",
            "Description": null,
            "Id": 0
        },
        "HasPromotion": false,
        "HasMemberCard": false,
        "MemberCardDiscount": null,
        "Latitude": 21.0305330000000,
        "Longitude": 105.8167930000000,
        "ResUsername": null,
        "ResCreatedOn": "\/Date(-62135596800000)\/",
        "LstPicture": null,
        "LstReview": [{
            "reviewProfileUrl": "/thanh-vien/duongthao.dav",
            "reviewUserDisplayName": "Thảo Dương",
            "reviewUserAvatar": "https://media.foody.vn/usr/g140/1396054/avt/c100x100/foody-avatar-782-636340741026389445.jpg",
            "reviewUrl": "/ha-noi/nha-hang-com-123-kim-ma/binh-luan-1715814",
            "AvgRatingText": "3.6",
            "ShortReview": false,
            "ReviewId": 1715814,
            "Comment": "Vừa gọi 2 suất trưa nay và cảm nhận là rất phí tiền =.= Mình gọi cơm mực sốt chua ngọt + cơm sườn nướng thì:\n\n- Sườn nhũn, ko ngon\n- Mực bọc bột nên ko ngấm gia vị, sốt thì quá ngọt ăn xong vẫn ngấy tận ...",
            "UserId": 1396054,
            "Username": "Dương",
            "UserAvatar": "foody-avatar-782-636340741026389445.jpg",
            "UserGender": "F",
            "UserFirstName": "Thảo",
            "UserLastName": "Dương",
            "AvgRating": 3.600000
        }, {
            "reviewProfileUrl": "/thanh-vien/nguyencham",
            "reviewUserDisplayName": "minhcham",
            "reviewUserAvatar": "https://media.foody.vn/usr/g957/9566984/avt/c100x100/nguyencham-avatar-671-636433604625175078.jpg",
            "reviewUrl": "/ha-noi/nha-hang-com-123-kim-ma/binh-luan-1712801",
            "AvgRatingText": "7.2",
            "ShortReview": false,
            "ReviewId": 1712801,
            "Comment": "Hôm trước mình có gọi suất mỳ bò và nước chanh ăn trưa vì nhỡ nhàng và địa chỉ nhà hàng gần cơ quan. Về chất lượng đồ ăn, mình thấy không thực sự ngon nhưng cũng tạm chấp nhận được lúc đang đói :) Đồ ...",
            "UserId": 9566984,
            "Username": "",
            "UserAvatar": "nguyencham-avatar-671-636433604625175078.jpg",
            "UserGender": "F",
            "UserFirstName": "minhcham",
            "UserLastName": "",
            "AvgRating": 7.200000
        }],
        "LstCategory": null,
        "LstCuisine": null,
        "PriceMin": null,
        "PriceMax": null,
        "PriceMinDisplay": null,
        "PriceMaxDisplay": null,
        "DisplayOrder": null,
        "City": null,
        "District": null,
        "FAvgRating": 7,
        "FTotalReviews": 87,
        "ResUrlAlbums": "/ha-noi/nha-hang-com-123-kim-ma/album-anh",
        "ResUrlReviews": "/ha-noi/nha-hang-com-123-kim-ma/binh-luan",
        "ContributeStatus": null,
        "CanDelete": false,
        "ListOwnerId": 0,
        "ListId": 0,
        "UserId": 0,
        "IsRestaurantCollection": false,
        "Services": [{
            "Id": 1,
            "Type": 0,
            "Url": "https://www.deliverynow.vn/ha-noi/nha-hang-com-123-kim-ma",
            "Title": "deliverynow.vn",
            "Text": "Giao tận nơi",
            "Avatar": "//static.foody.vn/s1/style/images/40x40_icon-deliverynow.png",
            "BackgroundColor": "#CE332F",
            "RestaurantId": 8920,
            "Description": null
        }],
        "TotalService": 1,
        "UrlRewriteName": "nha-hang-com-123-kim-ma",
        "LocationUrlRewriteName": "ha-noi",
        "RestaurantId": 8920,
        "MainCategoryId": 0,
        "TotalSaves": 236,
        "Status": 0,
        "TotalSavesFormat": "236",
        "TotalReviewsFormat": "87",
        "TotalPicturesFormat": "272",
        "IsAds": true,
        "MobileBgColor": "       ",
        "IsBooking": false,
        "IsDelivery": true,
        "BookingUrl": "",
        "DeliveryUrl": "/ha-noi/nha-hang-com-123-kim-ma/goi-mon",
        "HasVideo": false,
        "HasBooking": false,
        "HasDelivery": false,
        "MasterCategoryId": 1,
        "PromotionId": null,
        "PromotionTitle": null
    }],
    "Count": 12,
    "Total": 11520,
    "LastId": null
}
