<?php header('content-type: application/json'); ?>
[
    {
        "id": "node1",
        "title": "Node 1",
        "latitude": 21.02003,
        "longitude": 105.799,
        "price": 12000,
        "area": 100.0,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Trai",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Dong",
        "sophongngu": 2,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hung",
        "diachi": "Ha Noi",
        "dienthoai": "09121231",
        "didong": "102313",
        "email": "haquochung@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typeid": 2,
        "userid": "user1",
        "type": "restaurant",
        "duanid": "duan1",
        "modid": "mod1"
    },
    {
        "id": "node2",
        "title": "Node 2",
        "latitude": 21.02002,
        "longitude": 105.7998,
        "price": 12000,
        "area": 90.0,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Dong",
        "sophongngu": 2,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typeid": 1,
        "userid": "user2",
        "type": "restaurant",
        "duanid": "duan2",
        "modid": "mod1"
    },
    {
        "id": "node3",
        "title": "Node 3",
        "latitude": 21.0201,
        "longitude": 105.8,
        "price": 12000,
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typeid": 1,
        "userid": "user2",
        "type": "restaurant",
        "duanid": "duan1",
        "modid": "mod1"
    },
    {
        "id": "node4",
        "title": "Node 4",
        "latitude": 21.0201,
        "longitude": 105.7998,
        "price": 12000,
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typeid": 1,
        "userid": "user2",
        "type": "restaurant",
        "duanid": "duan1",
        "modid": "mod1"
    },
    {
        "id": "node5",
        "title": "Node 5",
        "latitude": 21.0200001,
        "longitude": 105.8,
        "price": 12000,
        "area": 80.03,
        "tinh": "Ha Noi",
        "huyen": "Thanh Xuan",
        "xa": "",
        "duong": "Nguyen Chi Thanh",
        "sonha": "15",
        "ngo": "",
        "ngach": "",
        "hem": "",
        "huong": "Nam",
        "sophongngu": 3,
        "details": "Gia re cam ket",
        "status": true,
        "normal_image": "as.jpg",
        "streetview_image": "assd.jpg",
        "tenlienhe": "hien",
        "diachi": "Ha Noi",
        "dienthoai": "09101231",
        "didong": "102313",
        "email": "haduchien@gmail.com",
        "rank": 1,
        "timefrom": "2017-08-12",
        "timeto": "2017-08-20",
        "typeid": 4,
        "userid": "user2",
        "type": "restaurant",
        "duanid": "duan1",
        "modid": "mod1"
    }
]
